version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravote_devops_app
    ports:
      - "9000:9000"
    depends_on:
      - db
    restart: always

  web:
    image: nginx:stable
    container_name: laravote_devops_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always

  db:
    image: mysql:5.7
    container_name: laravote_devops_db
    restart: always
    environment:
      MYSQL_DATABASE: laravote
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
