name: Deploy to VM

on:
  ## trigger kalau pipeline/workflow test.yml complete
  workflow_run:
    workflows: ["Laravel CI"]
    types:
      - completed

  ## bukan trigger, jadi bisa secara manual juga lewat UI nya github
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Pull Project on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            cd ~/laravote_devops
            git pull origin master

      - name: Rebuild Containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            cd ~/laravote_devops
            docker-compose down #kalo dipake nanti db nya hilang
            docker-compose up -d --build

      - name: Migrate Database
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            cd ~/laravote_devops
            docker-compose exec app php artisan migrate --force

      # only run this if fresh deploy or data not populated yet
      - name: Seeder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            cd ~/laravote_devops
            docker-compose exec app php artisan db:seed --force

      - name: Set Folder Permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            cd ~/laravote_devops
            docker-compose exec app chown -R www-data:www-data storage bootstrap/cache
            docker-compose exec app chmod -R 775 storage bootstrap/cache

      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            sudo systemctl reload nginx || sudo systemctl restart nginx
